 Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT License.



 # Randomly generated CyberBattle network environment for Active Directory

In [1]:
import cyberbattle.samples.active_directory.generate_ad as ad
import cyberbattle.simulation.commandcontrol as commandcontrol
import logging, sys, random

random.seed(1)
logging.basicConfig(stream=sys.stdout, level=logging.INFO, format="%(levelname)s: %(message)s")
# %matplotlib inline

In [2]:
env = ad.new_random_environment(42)
env.plot_environment_graph()

In [3]:
c2 = commandcontrol.CommandControl(env)
dbg = commandcontrol.EnvironmentDebugging(c2)

# 1 - Start from client
dbg.plot_discovered_network()
c2.print_all_attacks()

,status,properties,local_attacks,remote_attacks
id,,,,
workstation_0,owned,[breach_node],"[EnumerateFileShares, FindDomainControllers, P...",[]

In [4]:
outcome = c2.run_attack("workstation_0", "FindDomainControllers")
dbg.plot_discovered_network()
c2.print_all_attacks()

INFO: discovered node: domain_controller_1
INFO: GOT REWARD: Found domain controllers

,status,properties,local_attacks,remote_attacks
id,,,,
workstation_0,owned,[breach_node],"[EnumerateFileShares, FindDomainControllers, P...",[]
domain_controller_1,discovered,NaN,None,[]

In [5]:
outcome = c2.run_attack("workstation_0", "EnumerateFileShares")
dbg.plot_discovered_network()
c2.print_all_attacks()

INFO: discovered node: share_0
INFO: GOT REWARD: Found shares

,status,properties,local_attacks,remote_attacks
id,,,,
workstation_0,owned,[breach_node],"[EnumerateFileShares, FindDomainControllers, P...",[]
domain_controller_1,discovered,NaN,None,[]
share_0,discovered,NaN,None,[]

In [6]:
outcome = c2.run_attack("workstation_0", "AuthorizationSpoofAndCrack")
dbg.plot_discovered_network()
c2.print_all_attacks()

INFO: discovered node: share_0
INFO: discovered credential: CachedCredential(node='share_0', port='SMB', credential='user_8')
INFO: discovered node: share_0
INFO: discovered credential: CachedCredential(node='share_0', port='SMB', credential='user_14')
INFO: discovered node: share_0
INFO: discovered credential: CachedCredential(node='share_0', port='SMB', credential='user_47')
INFO: discovered node: workstation_3
INFO: discovered credential: CachedCredential(node='workstation_3', port='SHELL', credential='user_8')
INFO: discovered node: workstation_4
INFO: discovered credential: CachedCredential(node='workstation_4', port='SHELL', credential='user_14')
INFO: discovered node: workstation_2
INFO: discovered credential: CachedCredential(node='workstation_2', port='SHELL', credential='user_47')
INFO: GOT REWARD:

,status,properties,local_attacks,remote_attacks
id,,,,
workstation_0,owned,[breach_node],"[EnumerateFileShares, FindDomainControllers, P...",[]
domain_controller_1,discovered,NaN,None,[]
share_0,discovered,NaN,None,[]
workstation_3,discovered,NaN,None,[]
workstation_4,discovered,NaN,None,[]
workstation_2,discovered,NaN,None,[]

In [7]:
c2.connect_and_infect("workstation_0", "workstation_4", "SHELL", "user_28")
dbg.plot_discovered_network()
c2.print_all_attacks()

ValueError: Agent has not discovered credential 'user_28'

In [ ]:
c2.run_attack("workstation_4", "ScanForCreds")
dbg.plot_discovered_network()
c2.print_all_attacks()

In [ ]:
c2.connect_and_infect("workstation_0", "domain_controller_1", "AD", "dc_1")
dbg.plot_discovered_network()
c2.print_all_attacks()

In [ ]:
c2.run_attack("domain_controller_1", "DumpNTDS")
dbg.plot_discovered_network()
c2.print_all_attacks()